---
name: Test Khiops Native Interface
description: Action to test KNI package
runs:
  using: composite
  steps:
    - name: Check ldconfig
      shell: bash
      if: runner.os == 'Linux'
      run: |
        if [ $(ldconfig -p | grep -c KhiopsNativeInterface) -eq 0 ] 
        then
          echo "::error::KNI is not reachable with ld, check post installation"
          false
        fi
    - name: Checkout sources
      uses: actions/checkout@v4
      with:
        path: khiops
    - name: Checkout KhiopsNativeInterface-tutorial
      uses: actions/checkout@v4
      with:
        repository: KhiopsML/KhiopsNativeInterface-tutorial
        path: tutorial
    - name: Compile C examples (Linux)
      shell: bash
      if: runner.os == 'Linux'
      run: |
        cd tutorial
        bash $GITHUB_WORKSPACE/packaging/common/KNI/build-c-linux.sh
    - name: Compile C examples (Windows)
      if: runner.os == 'Windows'
      shell: cmd
      run: |
        call "C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Auxiliary\\Build\\vcvars64.bat"
        cd tutorial
        set KNI_HOME=%GITHUB_WORKSPACE%/KNI
        call %GITHUB_WORKSPACE%/packaging/common/KNI/build-c-windows.cmd
    - name: Run mono-table example (Linux)
      if: runner.os == 'Linux'
      shell: bash
      run: |
        ./tutorial/KNIRecodeFile tutorial/data/ModelingIris.kdic SNB_Iris tutorial/data/Iris.txt R_Iris.txt || true
    - name: Run mono-table example (Windows)
      if: runner.os == 'Windows'
      shell: cmd
      run: |
        set path=%GITHUB_WORKSPACE%/KNI/bin;%path%
        call %GITHUB_WORKSPACE%/tutorial/KNIRecodeFile.exe tutorial/data/ModelingIris.kdic SNB_Iris tutorial/data/Iris.txt R_Iris.txt
    - name: Check mono-table example
      shell: bash
      run: |
        if [ ! -f R_Iris.txt ] ;
        then
          echo "::error::R_Iris.txt is missing"
          false
        fi
        if diff -q R_Iris.txt khiops/packaging/common/KNI/results.ref/R_Iris.txt > /dev/null ; 
        then
          echo "Mono table recoding is OK"
        else
          echo "::error::Recoding issue with Iris.txt"
          false
        fi
    - name: Run multi-tables example (Linux)
      if: runner.os == 'Linux'
      shell: bash
      run: |-
        ./tutorial/KNIRecodeMTFiles -d tutorial/data/ModelingSpliceJunction.kdic SNB_SpliceJunction \
            -i tutorial/data/SpliceJunction.txt 1 -s DNA  tutorial/data/SpliceJunctionDNA.txt 1 -o R_SpliceJunction.txt || true
    - name: Run multi-tables example (Windows)
      if: runner.os == 'Windows'
      shell: cmd
      run: |-
        set path=%GITHUB_WORKSPACE%/KNI/bin;%path%
        call %GITHUB_WORKSPACE%/tutorial/KNIRecodeMTFiles.exe -d tutorial/data/ModelingSpliceJunction.kdic SNB_SpliceJunction ^
        -i tutorial/data/SpliceJunction.txt 1 -s DNA  tutorial/data/SpliceJunctionDNA.txt 1 -o R_SpliceJunction.txt
    - name: Check multi-table example
      shell: bash
      run: |
        if [ ! -f R_SpliceJunction.txt ] ;
        then
          echo "::error::R_SpliceJunction.txt is missing"
          false
        fi
        if diff -q R_SpliceJunction.txt khiops/packaging/common/KNI/results.ref/R_SpliceJunction.txt > /dev/null ; 
        then
          echo "Multi table recoding is OK"
        else
          echo "::error::Recoding issue with SpliceJunction.txt"
          false
        fi
    - name: setup jna
      shell: bash
      run: |
        curl https://repo1.maven.org/maven2/net/java/dev/jna/jna/5.13.0/jna-5.13.0.jar --output ./tutorial/jna.jar
    - name: Compile java example
      shell: bash
      run: |
        cd tutorial
        bash  $GITHUB_WORKSPACE/packaging/common/KNI/build-java.sh
    - name: Run java example (Linux)
      shell: bash
      if: runner.os == 'Linux'
      run: |
        cd tutorial
        bash $GITHUB_WORKSPACE/packaging/common/KNI/run-java-linux.sh
    - name: Test java example (Windows)
      shell: cmd
      if: runner.os == 'Windows'
      run: |
        cd tutorial
        set KNI_HOME=%GITHUB_WORKSPACE%/KNI
        call %GITHUB_WORKSPACE%/packaging/common/KNI/run-java-windows.cmd
    - name: Check java results
      shell: bash
      run: |-
        if [ ! -f tutorial/R_Iris_java.txt ] ;
        then
          echo "::error::R_Iris_java.txt is missing"
          false
        fi
        if diff -q tutorial/R_Iris_java.txt  packaging/common/KNI/results.ref/R_Iris.txt > /dev/null ; 
        then
          echo "Mono table recoding is OK"
          true
        else
          echo "::error::Recoding issue with java"
          false
        fi
