#!/bin/bash
KHIOPS_VERSION="0.0.0"
KHIOPS_REDUCED_VERSION="0.0.0"
ASSETS_DIR=/home/boeg7312/Téléchargements/khiops-win-install-assets-10.2.4/assets/
MSMPI_FILENAME=msmpisetup.exe
MSMPI_VERSION=0.0.0
KHIOPS_VIZ_FILENAME=khiops-visualization-Setup-11.0.9.exe
KHIOPS_COVIZ_FILENAME=khiops-covisualization-Setup-11.1.2.exe
KHIOPS_WINDOWS_BUILD_DIR=/home/boeg7312/Documents/windows/
makensis \
    -V4 \
    -DKHIOPS_VERSION=$KHIOPS_VERSION \
    -DKHIOPS_REDUCED_VERSION=$KHIOPS_REDUCED_VERSION \
    -DKHIOPS_WINDOWS_BUILD_DIR=$KHIOPS_WINDOWS_BUILD_DIR \
    -DJRE_PATH=$ASSETS_DIR/jre \
    -DMSMPI_INSTALLER_PATH=$ASSETS_DIR/$MSMPI_FILENAME \
    -DMSMPI_VERSION=$MSMPI_VERSION \
    -DKHIOPS_VIZ_INSTALLER_PATH=$ASSETS_DIR/$KHIOPS_VIZ_FILENAME \
    -DKHIOPS_COVIZ_INSTALLER_PATH=$ASSETS_DIR/$KHIOPS_COVIZ_FILENAME \
    -DKHIOPS_SAMPLES_DIR=$ASSETS_DIR/samples \
    -DKHIOPS_DOC_DIR=$ASSETS_DIR/doc \
    /home/boeg7312/dvpt/khiops-v11/packaging/windows/nsis/khiops.nsi
