#!/bin/bash

# Run Khiops tool
# see the khiops_env script for full documentation on the environment variables used by Khiops



error() {
    if [ -f /dev/log ]; then
        logger "$*" --tag khiops --stderr
    fi
    if [ -n "$DISPLAY" ]
    then
        notify-send "Khiops" "$*" -i /usr/share/pixmaps/khiops.png -u normal;
    fi
    exit 1; 
}


warning() {
    if [ -f /dev/log ]; then
        logger "$*" --tag khiops --stderr
    fi
    if [ -n "$DISPLAY" ]
    then
        notify-send "Khiops" "$*" -i /usr/share/pixmaps/khiops.png -u normal;
    fi
}

if [[ ! -f /usr/bin/khiops-env ]]; then
    error "/usr/bin/khiops-env is missing"
fi

# initialize Khiops environment
source /usr/bin/khiops-env

# Test if batch mode from parameters
KHIOPS_BATCH_MODE=false
for ((i=1;i<=$#;i++)); 
do
    if [ ${!i} = "-b" ]; then
	    KHIOPS_BATCH_MODE=true
        break
    fi
done;


if [[ ! -e $KHIOPS_PATH/MODL ]]; then
    error "Binary not found ($KHIOPS_PATH/MODL)"
fi

# Test multiple possible errors with the java GUI 
if [  "$KHIOPS_BATCH_MODE" = false ]; then
    if [ -z "$DISPLAY" ]; then
        error "GUI is not available, please use the '-b' flag"
    elif [ -z "$KHIOPS_JAVA_PATH" ]; then
        if [ -z "$KHIOPS_JAVA_ERROR" ]; then
            error "The khiops GUI is not configured properly. Please (re)install the 'khiops' package."
        else
            error "$KHIOPS_JAVA_ERROR"
        fi
    fi
fi

# Display error with mpi configuration
if [ -n "$KHIOPS_MPI_ERROR" ]; then
    warning "$KHIOPS_MPI_ERROR"
fi

export CLASSPATH=$CLASSPATH:$KHIOPS_CLASSPATH
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$KHIOPS_JAVA_PATH

if [[  $# -eq 0  ]]; then
    # run without parameters
    # run and save scenario and log files in directory KHIOPS_LAST_RUN_DIR
    $KHIOPS_MPI_COMMAND MODL -o "${KHIOPS_LAST_RUN_DIR}"/scenario._kh -e "${KHIOPS_LAST_RUN_DIR}"/log.txt
else
    # run with parameters
    $KHIOPS_MPI_COMMAND MODL "$@"
fi

exit $?
