---
name: "Build Khiops"

inputs:
  preset-name:
    description: "The CMake preset name"
    required: true
  override-flags:
    description: "List of overriding flags for the preset defaults (ex: '-DUSE_MPI=OFF -DBUILD_JARS=ON')"
  targets:
    description: "List of targets to be built (ex: 'MODL norm_test')"

runs:
  using: "composite"
  steps:
    - name: Setup MPI
      uses: mpi4py/setup-mpi@v1

    - name: Load Visual C++ Environment Variables (Windows only)
      if: ${{ runner.os == 'Windows' }}
      shell: cmd
      run: |
        call "C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Auxiliary\\Build\\vcvars64.bat"
        set >> %GITHUB_ENV%

    - name: Compile Khiops with CMake
      shell: bash
      run: |
        cmake --preset ${{ inputs.preset-name }} ${{ inputs.override-flags }}
        cmake --build --parallel --preset ${{ inputs.preset-name }} --target ${{ inputs.targets }}
