---
name: "Build Khiops"

on:
  workflow_call:
    inputs:
      preset-name:
        description: "The CMake preset name"
        required: true
      override-flags:
        description: "List of overriding flags for the preset defaults"

runs:
  using: "composite"
  steps:
    - name: Setup MPI
      uses: mpi4py/setup-mpi@v1

    - name: Load Visual C++ Environment Variables (Windows only)
      if: ${{ runner.os == 'Windows' }}
      shell: cmd
      run: |
        call "C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Auxiliary\\Build\\vcvars64.bat"
        set >> %GITHUB_ENV%

    - name: Install Ninja (Linux only)
      if: ${{ runner.os == 'Linux' }}
      shell: bash
      run: sudo apt-get install ninja-build

    - name: Compile Khiops with CMake
      shell: bash
      run: |
        cmake --preset ${{ inputs.preset-name }} ${{ inputs.override-flags }}
        cmake --build --preset build-${{ inputs.preset-name }}
