---
name: Test Khiops package
description: Action to test Khiops package on iris dataset
runs:
  using: composite
  steps:
    - name: Check Khiops installation
      shell: bash
      run: |
        khiops -v
        khiops_coclustering -v
    - name: Run Khiops tests
      shell: bash
      run: |
        cd test/LearningTest/TestKhiops/Standard/Iris/
        khiops -b -i test.prm -e results/err.txt
        cd -
    - name: Run Khiops Coclustering tests
      shell: bash
      run: |
        cd test/LearningTest/TestCoclustering/Standard/Iris/
        khiops_coclustering -b -i test.prm -e results/err.txt
        cd -
    # Installation of python, we don't use the setup-python action because whe have the error:
    # python3: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by python3)
    - name: Setup python
      shell: bash
      run: |
        if [ "$RUNNER_OS" == "Linux" ]
        then
           if [ -d "/etc/apt" ]
           then
             apt-get install -y python3 > /dev/null
           else
             yum install -y python3.11 
           fi
        fi
    - name: Check results
      shell: bash
      run: |-
        touch test/LearningTest/TestCoclustering/Standard/Iris/results/time.log
        touch test/LearningTest/TestKhiops/Standard/Iris/results/time.log
        cd test/LearningTest/cmd/python/
        python3 test_khiops.py Khiops nul Standard
        python3 test_khiops.py Coclustering nul Standard
        python3 apply_command.py errors ../../TestKhiops/Standard/ Iris | tee /tmp/khiops-log.txt
        python3 apply_command.py errors ../../TestCoclustering/Standard/ Iris | tee /tmp/coclustering-log.txt
        if (grep -q error /tmp/khiops-log.txt || grep -q error /tmp/coclustering-log.txt); then
          echo "::error::Errors in Khiops run"
          false
        fi
