#!/bin/bash
set -e

if [ ! -d "/opt/khiops/key" ]; then
    mkdir -p /opt/khiops/key/
fi

# khiops creates empty license file at the first run
# this file is owned by root, standard user should be able to modify it
chmod a+rw -R /opt/khiops/key/

# set mpich for default mpi
update-alternatives --set mpirun /usr/bin/mpirun.mpich



