---
name: Build all CMake targets
on:
  workflow_dispatch:
  pull_request:
    paths:
      - '**CMakeLists.txt'
      - src/**.h
      - src/**.cpp
      - src/**.java
      - src/**.dd
      - src/**.inc
      - src/**.lex
      - src/**.yac
      - test/**.h
      - test/**.cpp
jobs:
  build-all-targets:
    strategy:
      fail-fast: false
      matrix:
        build-setup:
          - {os: windows-2022, cmake-preset: windows-msvc-release}
          - {os: ubuntu-latest, cmake-preset: linux-gcc-release}
          - {os: macos-latest, cmake-preset: macos-clang-release}
    runs-on: ${{ matrix.build-setup.os }}
    steps:
      - name: Checkout Khiops sources
        uses: actions/checkout@v3
      - name: Build all CMake targets
        uses: ./.github/actions/build-khiops
        with:
          preset-name: ${{ matrix.build-setup.cmake-preset }}
          override-flags: -DBUILD_JARS=ON -DGENERATE_VIEWS=ON
