---
name: Create RPM package
on:
  workflow_dispatch:
jobs:
  package-rpm:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [rocky8, rocky9]
    container:
      image: ghcr.io/khiopsml/khiops/${{ matrix.os }}:latest
    steps:
      - uses: actions/checkout@v3
      - name: set environment variables
        run: |
          source /etc/os-release 
          echo "ID=$ID" >> "$GITHUB_ENV"
          VERSION=$(echo $PLATFORM_ID | cut -d":" -f2)
          echo "VERSION=$VERSION" >> "$GITHUB_ENV"
      - name: Configure CMake
        run: |
          source /etc/profile.d/modules.sh
          module load mpi/mpich-x86_64
          echo "MPI_SUFFIX=$MPI_SUFFIX" >> "$GITHUB_ENV"
          cmake -B build -S . -DCMAKE_BUILD_TYPE=Release -DTESTING=OFF -DBUILD_JARS=ON -DFEDORA=ON
      - name: Build Khiops executables
        run: cmake --build build --parallel --target MODL${{ env.MPI_SUFFIX }} MODL_Coclustering
          KhiopsNativeInterface
      - name: Build package with CPack
        run: cd build && cpack -G RPM
      - name: Upload artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          name: ${{ env.ID }}-${{ env.VERSION }}
          path: build/packages/*.rpm
          if-no-files-found: error
