---
name: Create RPM package
on:
  workflow_dispatch:
  push:
    branches: [47-improve-and-test-kni-packages]
jobs:
  package-rpm:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        os: [rocky8, rocky9]
    container:
      image: ghcr.io/khiopsml/khiops/${{ matrix.os }}:latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: set environment variables
        run: |
          source /etc/os-release 
          echo "ID=$ID" >> "$GITHUB_ENV"
          VERSION=$(echo $PLATFORM_ID | cut -d":" -f2)
          echo "VERSION=$VERSION" >> "$GITHUB_ENV"
      - name: Configure CMake
        run: |
          source /etc/profile.d/modules.sh
          module load mpi/mpich-x86_64
          echo "MPI_SUFFIX=$MPI_SUFFIX" >> "$GITHUB_ENV"
          cmake -B build -S . -DCMAKE_BUILD_TYPE=Release -DTESTING=OFF -DBUILD_JARS=ON
      - name: Build Khiops executables
        run: |
          cmake --build build --parallel --target MODL${{ env.MPI_SUFFIX }} MODL_Coclustering${{ env.MPI_SUFFIX }} KhiopsNativeInterface
      - name: Build package with CPack
        run: cd build && cpack -G RPM
      - name: Upload artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          name: ${{ env.ID }}-${{ env.VERSION }}
          path: build/packages/*.rpm
          if-no-files-found: error
  # Test packages on a brand new runner: we want to check the installation process (with the dependencies installation)
  # and the Khiops execution on a simple dataset
  test-khiops-rpm:
    needs: package-rpm
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        os: [8, 9]
    container:
      image: rockylinux:${{ matrix.os }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Set environment variables
        run: |
          source /etc/os-release 
          echo "ID=$ID" >> "$GITHUB_ENV"
          VERSION=$(echo $PLATFORM_ID | cut -d":" -f2)
          echo "VERSION=$VERSION" >> "$GITHUB_ENV"
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.ID }}-${{ env.VERSION}}
          path: artifacts
      - run: yum update -y
      - name: Install Khiops core
        run: |
          yum install -y ./artifacts/khiops-core* 
      - name: Install Khiops (with java)
        run: |
          yum install -y ./artifacts/khiops-*
      - name: Test Khiops and Khiops Coclustering
        uses: ./.github/actions/test-khiops
  test-kni-rpm:
    needs: package-rpm
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        os: [rocky8, rocky9]
    container:
      image: ghcr.io/khiopsml/khiops/${{ matrix.os }}:latest
    steps:
      - name: Set environment variables
        run: |
          source /etc/os-release 
          echo "ID=$ID" >> "$GITHUB_ENV"
          VERSION=$(echo $PLATFORM_ID | cut -d":" -f2)
          echo "VERSION=$VERSION" >> "$GITHUB_ENV"
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.ID }}-${{ env.VERSION }}
          path: artifacts
      - name: Install KNI
        run: |
          yum update -y
          yum install -y ./artifacts/kni* 
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          sparse-checkout: .github
      - name: Test KNI
        uses: ./.github/actions/test-kni
