---
name: pip packaging
on:
  workflow_dispatch:
    inputs:
      python_repository:
        description: python repository
        type: choice
        default: None  # no publishing to any Package Index by default
        options: [None, testpypi, pypi]
      signature-activation:
        type: boolean
        required: true
        default: false
        description: Sign Windows binaries in khiops-core and khiops-kni wheels
  push:
    tags: ['*']
  pull_request:
    paths:
      - '**CMakeLists.txt'
      - '!test/**CMakeLists.txt'
      - '**.cmake'
      - .github/workflows/pack-pip.yml
      - packaging/pip/pyproject-khiops.toml
      - packaging/pip/pyproject-kni.toml
      - packaging/pip/pyproject-knitransfer.toml
defaults:
  run:
    shell: bash
env:
  KEYPAIR: KP_Khiops_HSM
jobs:
  build-wheel:
    name: Build wheel
    runs-on: ${{ matrix.os }}
    # intel-mpi is not available for arm64, so we can not build the wheel for windows-11-arm
    strategy:
      matrix:
        os:
          - ubuntu-24.04
          - ubuntu-24.04-arm
          - windows-2025-vs2026
          - macos-15-intel
          - macos-15
    steps:
      - uses: actions/checkout@v6
      - name: Move pyproject-khiops file to the root of the repository
        run: |
          mv packaging/pip/pyproject-khiops.toml pyproject.toml
      - name: Load Visual C++ Environment Variables (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          call "C:\\Program Files\\Microsoft Visual Studio\\18\\Enterprise\\VC\\Auxiliary\\Build\\vcvars64.bat"
          set >> %GITHUB_ENV%
      - name: Build wheels
        uses: pypa/cibuildwheel@v3.4.1
      - name: install Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'
      - name: Install built wheel in a custom directory
        run: |
          KHIOPS_INSTALL_DIR="${{ runner.temp }}/khiops-env"
          echo "KHIOPS_INSTALL_DIR=$KHIOPS_INSTALL_DIR" >> "$GITHUB_ENV"
          python -m venv "$KHIOPS_INSTALL_DIR"
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            source "$KHIOPS_INSTALL_DIR/Scripts/activate"
          else
            source "$KHIOPS_INSTALL_DIR/bin/activate"
          fi
          python -m pip install --find-links=wheelhouse khiops-core
          pip show -f khiops-core
      - name: Export BIN_DIR
        id: export_bin_dir
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            echo "BIN_DIR=$KHIOPS_INSTALL_DIR/Scripts" >> "$GITHUB_OUTPUT"
          else
            echo "BIN_DIR=$KHIOPS_INSTALL_DIR/bin" >> "$GITHUB_OUTPUT"
          fi
      - name: Check Khiops core installation
        uses: ./.github/actions/test-khiops-install
        with:
          binary-path: ${{ steps.export_bin_dir.outputs.BIN_DIR }}
      - name: Move pyproject-kni file to the root of the repository
        run: |
          mv packaging/pip/pyproject-kni.toml pyproject.toml
      - name: Build kni wheels
        uses: pypa/cibuildwheel@v3.4.1
      - name: Move pyproject-knitransfer file to the root of the repository
        run: |
          mv packaging/pip/pyproject-knitransfer.toml pyproject.toml
      - name: Build knitransfer wheels
        uses: pypa/cibuildwheel@v3.4.1
      - uses: actions/upload-artifact@v7
        if: runner.os != 'Windows'
        with:
          name: pkg-wheel-${{ matrix.os }}
          path: wheelhouse/*.whl
          if-no-files-found: error
      - uses: actions/upload-artifact@v7
        if: runner.os == 'Windows'
        with:
          name: wheelhouse-windows-unsigned
          path: wheelhouse/*.whl
          if-no-files-found: error
  sign-wheel-windows:
    name: Sign Windows wheels
    needs: [build-wheel]
    runs-on: windows-2025-vs2026
    env:
      SIGN_WINDOWS_WHEELS: ${{ github.event_name == 'workflow_dispatch' && inputs.signature-activation }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/download-artifact@v8
        with:
          name: wheelhouse-windows-unsigned
          path: wheelhouse
      - name: Install Python
        if: env.SIGN_WINDOWS_WHEELS == 'true'
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'
      - name: Install wheel package
        if: env.SIGN_WINDOWS_WHEELS == 'true'
        run: python -m pip install wheel
      - name: Unpack khiops-core and khiops-kni wheels
        if: env.SIGN_WINDOWS_WHEELS == 'true'
        run: |
          mkdir -p wheelhouse/unpacked
          python -m wheel unpack wheelhouse/khiops_core-*.whl --dest wheelhouse/unpacked
          python -m wheel unpack wheelhouse/khiops_kni-*.whl --dest wheelhouse/unpacked
      - name: Setup SM_CLIENT_CERT_FILE from base64 secret data
        if: env.SIGN_WINDOWS_WHEELS == 'true'
        run: |
          echo "SM_CLIENT_CERT_FILE=D:\\Certificate_pkcs12.p12" >> "$GITHUB_ENV"
          echo "${{ secrets.SM_CLIENT_CERT_FILE_B64 }}" | base64 --decode > /d/Certificate_pkcs12.p12
      - name: Sign unpacked wheel binaries
        if: env.SIGN_WINDOWS_WHEELS == 'true'
        uses: digicert/code-signing-software-trust-action@v1.2.1
        with:
          input: wheelhouse/unpacked/
          keypair-alias: ${{ env.KEYPAIR }}
          simple-signing-mode: true
        env:
          SM_HOST: ${{ secrets.SM_HOST }}
          SM_API_KEY: ${{ secrets.SM_API_KEY }}
          SM_CLIENT_CERT_PASSWORD: ${{ secrets.SM_CLIENT_CERT_PASSWORD }}
      - name: Repack signed wheels
        if: env.SIGN_WINDOWS_WHEELS == 'true'
        run: |
          rm wheelhouse/khiops_core-*.whl
          rm wheelhouse/khiops_kni-*.whl
          python -m wheel pack wheelhouse/unpacked/khiops_core-* --dest-dir wheelhouse
          python -m wheel pack wheelhouse/unpacked/khiops_kni-* --dest-dir wheelhouse
      - uses: actions/upload-artifact@v7
        with:
          name: pkg-wheel-windows-2025-vs2026
          path: wheelhouse/*.whl
          if-no-files-found: error
  test-khiops-core-wheel:
    strategy:
      matrix:
        setup:
          - {os: ubuntu-24.04, image: ''}
          - {os: ubuntu-24.04-arm, image: ''}
          - {os: ubuntu-22.04, image: rockylinux:9}
          - {os: windows-2025-vs2026, image: ''}
          - {os: macos-15, image: ''}
          - {os: macos-15-intel, image: ''}
    runs-on: ${{ matrix.setup.os }}
    container: ${{ matrix.setup.image }}
    name: Test wheel
    needs: [build-wheel, sign-wheel-windows]
    steps:
      - uses: actions/checkout@v6
      - uses: actions/download-artifact@v8
        with:
          pattern: pkg-*
          path: wheelhouse
          merge-multiple: true
      - name: Python setup for Linux
        if: runner.os == 'Linux'
        shell: bash
        run: |
          # Install Python 3 if not present (already present in conda environment)
          if ! command -v python3 &> /dev/null
          then
            # Python install: we don't use the setup-python action because of the following error:
            # python3: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by python3)
            # Detect Debian based OS
            if [ -d "/etc/apt" ]
            then
              apt-get update
              apt-get install -y python3 > /dev/null
            else
              yum check-update || true
              yum install -y python3.11
            fi
          fi
          echo "PYTHON=python3" >> "$GITHUB_ENV"
      - name: Python setup for Windows or macOS
        if: runner.os == 'Windows' || runner.os == 'macOS'
        shell: bash
        run: echo "PYTHON=python" >> "$GITHUB_ENV"
      - name: Install built wheel in a custom directory
        id: install_khiops_core
        run: |
          KHIOPS_INSTALL_DIR="${{ runner.temp }}/khiops-env"
          $PYTHON -m venv "$KHIOPS_INSTALL_DIR"
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            source "$KHIOPS_INSTALL_DIR/Scripts/activate"
            echo "BIN_DIR=$KHIOPS_INSTALL_DIR/Scripts" >> "$GITHUB_OUTPUT"
          else
            source "$KHIOPS_INSTALL_DIR/bin/activate"
            echo "BIN_DIR=$KHIOPS_INSTALL_DIR/bin" >> "$GITHUB_OUTPUT"
          fi
          $PYTHON -m pip install --find-links=wheelhouse khiops-core
          $PYTHON -m pip show -f khiops-core
      - name: Run standard tests
        uses: ./.github/actions/run-standard-tests
        with:
          warning_as_error: true
          running-mode: parallel
          config: release
          binary-path: ${{ steps.install_khiops_core.outputs.BIN_DIR }}
          testing-context-description: pip-test-${{ matrix.setup.os }}-${{ matrix.setup.image
            }}
  test-kni:
    name: Test KNI Python wheel
    needs: [build-wheel, sign-wheel-windows]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-24.04
          - ubuntu-24.04-arm
          - windows-2025
          - macos-15-intel
          - macos-15
        python-version: ['3.10', '3.11', '3.12', '3.13', '3.14']
    steps:
      - uses: actions/checkout@v6
      - uses: actions/download-artifact@v8
        with:
          pattern: pkg-*
          path: wheelhouse
          merge-multiple: true
      - name: Checkout KhiopsNativeInterface-tutorial
        uses: actions/checkout@v6
        with:
          repository: KhiopsML/KhiopsNativeInterface-tutorial
          path: tutorial
          ref: main
      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install khiops-kni wheel
        run: python -m pip install --find-links=wheelhouse khiops-kni
      - name: Run python mono-table example
        shell: bash
        run: |
          cd tutorial
          bash $GITHUB_WORKSPACE/packaging/common/KNI/run-python.sh
      - name: Check python mono-table results
        shell: bash
        run: |
          if [ ! -f tutorial/R_Iris_python.txt ]; then
            echo "::error::R_Iris_python.txt is missing"
            false
          fi
          if diff -q tutorial/R_Iris_python.txt packaging/common/KNI/results.ref/R_Iris.txt > /dev/null; then
            echo "Python mono table recoding is OK"
          else
            echo "::error::Recoding issue with python"
            false
          fi
      - name: Run python multi-table example
        shell: bash
        run: |
          cd tutorial
          bash $GITHUB_WORKSPACE/packaging/common/KNI/run-multitable-python.sh
      - name: Check python multi-table results
        shell: bash
        run: |
          if [ ! -f tutorial/R_SpliceJunction_python.txt ]; then
            echo "::error::R_SpliceJunction_python.txt is missing"
            false
          fi
          if diff -q tutorial/R_SpliceJunction_python.txt packaging/common/KNI/results.ref/R_SpliceJunction.txt > /dev/null; then
            echo "Python multi table recoding is OK"
          else
            echo "::error::Recoding issue with python multi-table"
            false
          fi
  release-testpypi:
    # Publish only on tag pushes in the KhiopsML repository
    if: github.ref_type == 'tag' && github.repository_owner == 'KhiopsML' && inputs.python_repository
      == 'testpypi'
    name: Publish to Test.PyPI.org
    needs: [build-wheel, test-khiops-core-wheel, test-kni]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    environment:
      name: testpypi
    steps:
      - uses: actions/download-artifact@v8
        with:
          pattern: pkg-*
          path: dist
          merge-multiple: true
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
          repository-url: https://test.pypi.org/legacy/
  release-pypi:
    # Publish only on tag pushes in the KhiopsML repository
    name: Publish to PyPI.org
    if: github.ref_type == 'tag' && github.repository_owner == 'KhiopsML' && inputs.python_repository
      == 'pypi'
    needs: [build-wheel, test-khiops-core-wheel, test-kni]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    environment:
      name: pypi
    steps:
      - uses: actions/download-artifact@v8
        with:
          pattern: pkg-*
          path: dist
          merge-multiple: true
      - name: Remove knitransfer wheel from the distribution directory (we do not
          want to publish it on PyPI)
        run: |
          rm dist/*knitransfer*.whl
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
