---
name: Test Conda Packages
on:
  workflow_dispatch:
    inputs:
      khiops_version:
        type: string
        default: ''
        description: version of the package to test (e.g. 11.0.0-rc1). If null, the
          latest version will be tested.
      label:
        type: choice
        default: rc
        options: [main, rc]
        description: label of the package
defaults:
  run:
    shell: bash -el {0}
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        setup:
          - {os: ubuntu-22.04, image: ubuntu:20.04}
          - {os: ubuntu-22.04, image: ''}
          - {os: ubuntu-24.04, image: ''}
          - {os: ubuntu-22.04, image: rockylinux:8}
          - {os: ubuntu-22.04, image: rockylinux:9}
          - {os: windows-2022, image: ''}
          - {os: windows-2025, image: ''}
          - {os: macos-14, image: ''}
          - {os: macos-15, image: ''}
          - {os: macos-26, image: ''}
          - {os: macos-15-intel, image: ''}
    runs-on: ${{ matrix.setup.os }}
    container: ${{ matrix.setup.image }}
    steps:
      - name: Install Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          python-version: '3.12'
          channels: conda-forge
          conda-remove-defaults: true
      - name: Install the Khiops executables in the Conda environment
        run: |
          if [ -z "${{ inputs.khiops_version }}" ]; then
            echo "No version specified, installing the latest version of khiops-core"
            conda install -c conda-forge/label/${{ inputs.label }}  khiops-core
          else
            echo "Installing khiops-core version ${{ inputs.khiops_version }}"
            conda install -c conda-forge/label/${{ inputs.label }}  khiops-core=${{ inputs.khiops_version }}
          fi
      - name: Checkout sources
        uses: actions/checkout@v6
      - name: Export BIN_DIR
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            echo "BIN_DIR=$CONDA_PREFIX/Library/bin" >> "$GITHUB_ENV"
          else
            echo "BIN_DIR=$CONDA_PREFIX/bin" >> "$GITHUB_ENV"
          fi
      - name: Test that the Khiops executables are installed
        uses: ./.github/actions/test-khiops-install
        with:
          bin-dir: ${{ env.BIN_DIR }}
      - name: Test that the Khiops executables are functional
        uses: ./.github/actions/run-standard-tests
        with:
          warning_as_error: true
          running-mode: parallel
          config: release
          binary-path: ${{ env.BIN_DIR }}
          testing-context-description: ${{ matrix.setup.os }}-${{ matrix.setup.image
            }}
